//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yatra.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Core.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Deleted.
        /// </summary>
        public static string lbl_accountDeleted {
            get {
                return ResourceManager.GetString("lbl_accountDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Disabled.
        /// </summary>
        public static string lbl_accountDisabled {
            get {
                return ResourceManager.GetString("lbl_accountDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        public static string lbl_Cap_information {
            get {
                return ResourceManager.GetString("lbl_Cap_information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string lbl_Cap_success {
            get {
                return ResourceManager.GetString("lbl_Cap_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Class name is already exist !.
        /// </summary>
        public static string lbl_ClassNameExist {
            get {
                return ResourceManager.GetString("lbl_ClassNameExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string lbl_confirmpassword {
            get {
                return ResourceManager.GetString("lbl_confirmpassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Records fetched..
        /// </summary>
        public static string lbl_DataFetched {
            get {
                return ResourceManager.GetString("lbl_DataFetched", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device id is Different.
        /// </summary>
        public static string lbl_deviceId {
            get {
                return ResourceManager.GetString("lbl_deviceId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domain name already exist !.
        /// </summary>
        public static string lbl_domainNameExist {
            get {
                return ResourceManager.GetString("lbl_domainNameExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domain name not found !.
        /// </summary>
        public static string lbl_domainNameNotFound {
            get {
                return ResourceManager.GetString("lbl_domainNameNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address.
        /// </summary>
        public static string lbl_emailAddress {
            get {
                return ResourceManager.GetString("lbl_emailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Id is already in use..
        /// </summary>
        public static string lbl_emilIdInUse {
            get {
                return ResourceManager.GetString("lbl_emilIdInUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Id is empty!.
        /// </summary>
        public static string lbl_emptyDeviceID {
            get {
                return ResourceManager.GetString("lbl_emptyDeviceID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error!.
        /// </summary>
        public static string lbl_error {
            get {
                return ResourceManager.GetString("lbl_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your bulk request file is now successfully uploaded. In 20min all requests will be sent, so check in Pending Request page after 20min for status..
        /// </summary>
        public static string lbl_ExcelSuccess {
            get {
                return ResourceManager.GetString("lbl_ExcelSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exception!.
        /// </summary>
        public static string lbl_exception {
            get {
                return ResourceManager.GetString("lbl_exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export To Excel.
        /// </summary>
        public static string lbl_exportToExcel {
            get {
                return ResourceManager.GetString("lbl_exportToExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File(s).
        /// </summary>
        public static string lbl_files {
            get {
                return ResourceManager.GetString("lbl_files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grade name already exist !.
        /// </summary>
        public static string lbl_GradeNameExist {
            get {
                return ResourceManager.GetString("lbl_GradeNameExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grade name not found !.
        /// </summary>
        public static string lbl_GradeNameNotFound {
            get {
                return ResourceManager.GetString("lbl_GradeNameNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image not saved !.
        /// </summary>
        public static string lbl_image_not_saved {
            get {
                return ResourceManager.GetString("lbl_image_not_saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in.
        /// </summary>
        public static string lbl_in {
            get {
                return ResourceManager.GetString("lbl_in", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect domain name !.
        /// </summary>
        public static string lbl_IncorrectDomainName {
            get {
                return ResourceManager.GetString("lbl_IncorrectDomainName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect grade name !.
        /// </summary>
        public static string lbl_IncorrectGradeName {
            get {
                return ResourceManager.GetString("lbl_IncorrectGradeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input.
        /// </summary>
        public static string lbl_input {
            get {
                return ResourceManager.GetString("lbl_input", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal Server Error Occurred!.
        /// </summary>
        public static string lbl_internalServerErrorOccurred {
            get {
                return ResourceManager.GetString("lbl_internalServerErrorOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid.
        /// </summary>
        public static string lbl_invalid {
            get {
                return ResourceManager.GetString("lbl_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid ScanTime.
        /// </summary>
        public static string lbl_Invalid_ScanTime {
            get {
                return ResourceManager.GetString("lbl_Invalid_ScanTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Input Details !.
        /// </summary>
        public static string lbl_invalidInputs {
            get {
                return ResourceManager.GetString("lbl_invalidInputs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kiosk Id not found!.
        /// </summary>
        public static string lbl_InvalidKioskID {
            get {
                return ResourceManager.GetString("lbl_InvalidKioskID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token Validation Failed..
        /// </summary>
        public static string lbl_invalidToken {
            get {
                return ResourceManager.GetString("lbl_invalidToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Log.
        /// </summary>
        public static string lbl_log {
            get {
                return ResourceManager.GetString("lbl_log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account Does Not Exist.
        /// </summary>
        public static string lbl_msg_accountDoesNotExit {
            get {
                return ResourceManager.GetString("lbl_msg_accountDoesNotExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account not activated.
        /// </summary>
        public static string lbl_msg_accountNotActivated {
            get {
                return ResourceManager.GetString("lbl_msg_accountNotActivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Not Saved !.
        /// </summary>
        public static string lbl_msg_dataNotSavedSuccessfully {
            get {
                return ResourceManager.GetString("lbl_msg_dataNotSavedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Saved Successfully.
        /// </summary>
        public static string lbl_msg_dataSavedSuccessfully {
            get {
                return ResourceManager.GetString("lbl_msg_dataSavedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address Failed.
        /// </summary>
        public static string lbl_msg_emailAddressFailed {
            get {
                return ResourceManager.GetString("lbl_msg_emailAddressFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Address Required.
        /// </summary>
        public static string lbl_msg_eMailAddressRequired {
            get {
                return ResourceManager.GetString("lbl_msg_eMailAddressRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email and Password Required.
        /// </summary>
        public static string lbl_msg_emailPasswordRequired {
            get {
                return ResourceManager.GetString("lbl_msg_emailPasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incomplete Details !.
        /// </summary>
        public static string lbl_msg_IncompleteDetails {
            get {
                return ResourceManager.GetString("lbl_msg_IncompleteDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal Server Error Occurred.
        /// </summary>
        public static string lbl_msg_internalServerErrorOccurred {
            get {
                return ResourceManager.GetString("lbl_msg_internalServerErrorOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Email Address.
        /// </summary>
        public static string lbl_msg_invalidEmailAddress {
            get {
                return ResourceManager.GetString("lbl_msg_invalidEmailAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Email Address and Password.
        /// </summary>
        public static string lbl_msg_invalidEmailAddressPassword {
            get {
                return ResourceManager.GetString("lbl_msg_invalidEmailAddressPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Email ID OR Password.
        /// </summary>
        public static string lbl_msg_invalidEmpIdAddressPassword {
            get {
                return ResourceManager.GetString("lbl_msg_invalidEmpIdAddressPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Passowrd.
        /// </summary>
        public static string lbl_msg_invalidPassowrd {
            get {
                return ResourceManager.GetString("lbl_msg_invalidPassowrd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lbl_msg_loginFailed.
        /// </summary>
        public static string lbl_msg_loginFailed {
            get {
                return ResourceManager.GetString("lbl_msg_loginFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password change email sent.
        /// </summary>
        public static string lbl_msg_passwordChangeEmail {
            get {
                return ResourceManager.GetString("lbl_msg_passwordChangeEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string lbl_new {
            get {
                return ResourceManager.GetString("lbl_new", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Files Attached.
        /// </summary>
        public static string lbl_noFilesAttached {
            get {
                return ResourceManager.GetString("lbl_noFilesAttached", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Records Found.
        /// </summary>
        public static string lbl_noRecordsFound {
            get {
                return ResourceManager.GetString("lbl_noRecordsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Of.
        /// </summary>
        public static string lbl_of {
            get {
                return ResourceManager.GetString("lbl_of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page.
        /// </summary>
        public static string lbl_page {
            get {
                return ResourceManager.GetString("lbl_page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string lbl_password {
            get {
                return ResourceManager.GetString("lbl_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string lbl_profile {
            get {
                return ResourceManager.GetString("lbl_profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Records.
        /// </summary>
        public static string lbl_records {
            get {
                return ResourceManager.GetString("lbl_records", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Records Per Page.
        /// </summary>
        public static string lbl_recordsPerPage {
            get {
                return ResourceManager.GetString("lbl_recordsPerPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved successfully!.
        /// </summary>
        public static string lbl_saveSuccessfully {
            get {
                return ResourceManager.GetString("lbl_saveSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string lbl_search {
            get {
                return ResourceManager.GetString("lbl_search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success!.
        /// </summary>
        public static string lbl_success {
            get {
                return ResourceManager.GetString("lbl_success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successfully Created.
        /// </summary>
        public static string lbl_successfullyCreated {
            get {
                return ResourceManager.GetString("lbl_successfullyCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access unathorised !.
        /// </summary>
        public static string lbl_unauthorised {
            get {
                return ResourceManager.GetString("lbl_unauthorised", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User already Exist !.
        /// </summary>
        public static string lbl_UserExist {
            get {
                return ResourceManager.GetString("lbl_UserExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Not Found !.
        /// </summary>
        public static string lbl_UserNotFound {
            get {
                return ResourceManager.GetString("lbl_UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verson already Exist !.
        /// </summary>
        public static string lbl_version_exist {
            get {
                return ResourceManager.GetString("lbl_version_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disabled.
        /// </summary>
        public static string lbl_versionDisabled {
            get {
                return ResourceManager.GetString("lbl_versionDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version mismatched !.
        /// </summary>
        public static string lbl_versionError {
            get {
                return ResourceManager.GetString("lbl_versionError", resourceCulture);
            }
        }
        public static string lbl_noClassOrStudentFoundInGrade
        {
            get
            {
                return ResourceManager.GetString("lbl_noClassOrStudentFoundInGrade", resourceCulture);
            }
        }

        public static string lbl_teacherNotBelongsToClass
        {
            get
            {
                return ResourceManager.GetString("lbl_teacherNotBelongsToClass", resourceCulture);
            }
        }

        public static string lbl_somethingWentWrong
        {
            get
            {
                return ResourceManager.GetString("lbl_SomethingWentWrong", resourceCulture);
            }
        }
        public static string lbl_mobileNumberisinvalid
        {
            get
            {
                return ResourceManager.GetString("lbl_mobileNumberisinvalid", resourceCulture);
            }
        }
        public static string lbl_MobileNumberInUse
        {
            get
            {
                return ResourceManager.GetString("lbl_mobileNumberInUse", resourceCulture);
            }
        }

        public static string lbl_OTPGeneratedMessage
        {
            get
            {
                return ResourceManager.GetString("lbl_OTPGeneratedMessage", resourceCulture);
            }
        }

        public static string lbl_EmailLoginSuccessMessage
        {
            get
            {
                return ResourceManager.GetString("lbl_EmailLoginSuccessMessage", resourceCulture);
            }
        }

        public static string lbl_verifyOTPExpiredMessage
        {
            get
            {
                return ResourceManager.GetString("lbl_verifyOTPExpiredMessage", resourceCulture);
            }
        }
        public static string lbl_verifyOTPEnterValidOTPMessage
        {
            get
            {
                return ResourceManager.GetString("lbl_verifyOTPEnterValidOTPMessage", resourceCulture);
            }
        }

        public static string lbl_verifyOTPValidMessage
        {
            get
            {
                return ResourceManager.GetString("lbl_verifyOTPValidMessage", resourceCulture);
            }
        }
    }
}
